# docker-compose.yml

version: '3.9'

services:
  web:
    build: .
    container_name: ppp_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
    restart: always

  db:
    image: postgres:14
    container_name: ppp_db
    environment:
      POSTGRES_USER: ppp_user
      POSTGRES_PASSWORD: ppp_pass
      POSTGRES_DB: ppp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: